### ISSUE TITLE
Volumes add-on and Local 2.0 UI issues

### ISSUE THREAD

**Issue by benjaminprojas** [getflywheel/local-addon-volumes#4]
When opening the volume 2.0 admin screen, none of the current mapped volumes appear and it looks like all the styles are messed up:

![image](https://cloud.githubusercontent.com/assets/962530/26308283/8a995e26-3ec6-11e7-98ee-4ffeef047221.png)

I'm assuming it just needs to be updated to work with Local 2.0.

**Comment by afragen** [comment]
It also doesn't seem to work with Local 2.0. If you click in the fields and add back your paths, selecting _Remap Volumes_ seems to be stuck on provisioning.

**Comment by benjaminprojas** [comment]
@claygriffiths are there any simple fixes we can manually change to get this working again? You don't realize how much you rely on something until it doesn't work any more 😆 
Also, existing volumes on sites do seem to still work.

**Comment by JiveDig** [comment]
It won't let me install either.

<img width="907" alt="screen shot 2017-05-31 at 12 03 29 am" src="https://cloud.githubusercontent.com/assets/540990/26615427/b68a0664-4594-11e7-96e1-c6e4e5a0fb6e.png">

**Comment by afragen** [comment]
@JiveDig see #3  to install. But it doesn't work. 👎

**Comment by JiveDig** [comment]
Boo.

**Comment by afragen** [comment]
But now you can install it and help debug 😉

**Comment by JRGould** [comment]
Seeing the following in the debugging console: 

```
/Applications/Local by Flywheel.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:318 Uncaught TypeError: docker is not a function
    at SiteInfoVolumes.remapVolumes (~/Library/Application Support/Local by Flywheel/addons/local-addon-volumes/lib/SiteInfoVolumes.js:278:5)
...
```

Looks like the app's docker API has changed, but since the main codebase isn't open it's hard to navigate by just probing `context.docker` in the console.

Any plans on fixing this any time soon, @claygriffiths?

**Comment by tazeverywhere** [comment]
Dear @claygriffiths, 

It would be great to fix compatbility with Local v2.
This plugin seems to be the only solution to sync db between many local machines (cloud or btsync) , whithout the need to export each time or having an external staging server..

Btw, thx for the amazing Local app! A great tool and a perfect dev workflow with Wordmove.

All the best to the team

**Comment by MrSpecific** [comment]
Really rely on this plugin for my workflow, and super disappointed that Local 2.0 broke things. Any hope?

**Comment by Ipstenu** [comment]
Per https://local.getflywheel.com/community/t/volumes-add-on-not-working-in-version-2-0/1468/2 @claygriffiths says he's going to get this working soon.

This is 100% the primary reason I prefer Local over everything else, so add my name to the list. I'll be experimenting with Chassis however in the meantime.

**Comment by claygriffiths** [comment]
Thanks everyone for the feedback! This is now fixed in 1.1.0.

Here's the release: https://github.com/getflywheel/local-addon-volumes/releases/tag/1.1.0

And the commits:

037fa76197a21ab69209d0303df068f19e894a0f
3c7396e615a96d01016b084d008fe14ff094cace
ce17842141938858377a6ebbd82dd415ad792a7d

To upgrade simply swap out the volumes addon folder in `~/Library/Application Support/Local by Flywheel/addons`. You can get there quickly by clicking on the "Reveal" button under Preferences » Add-ons in Local.
